insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Martinez', 'OTRO' ,1);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Cargo Venezuela', 'OTRO' ,1);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Brothers Company', 'OTRO' ,2);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Tu Producto C.A.', 'OTRO' ,2);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Te lo tengo VE', 'OTRO' ,3);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Amigos y Familia inc.', 'OTRO' ,3);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Precios Alfa', 'OTRO' ,4);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Vete De Compras', 'OTRO' ,4);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Resuelve', 'OTRO' ,5);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'No Busques Más', 'OTRO' ,5);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Master Festejos', 'OTRO' ,6);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Don Obsequio', 'OTRO' ,6);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Santo Remedio', 'OTRO' ,7);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora A Tu Alcance C.A.', 'OTRO' ,7);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Mar y Sol', 'OTRO' ,8);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Doña Milly', 'OTRO' ,8);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Parties International', 'OTRO' ,9);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Sirvete Un Trago', 'ALIMENTOS' ,9);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Ponle Hielo', 'OTRO' ,10);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Moving Food', 'ALIMENTOS' ,10);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Hasta El Final', 'OTRO' ,11);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'El Último Chicharrón', 'OTRO' ,11);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Mar y Tierra', 'OTRO' ,12);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Damar', 'OTRO' ,12);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Come Con Calma', 'ALIMENTOS' ,13);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Te Lo LLevamos', 'OTRO' ,13);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Tú Primero', 'OTRO' ,14);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas La Victoria', 'OTRO' ,14);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Los Chinos', 'OTRO' ,15);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Dragón De Oro', 'OTRO' ,15);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas Botellón', 'OTRO' ,16);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'El Lugar De Las Telas', 'OTRO' ,16);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Fabricantes Venezuela', 'OTRO' ,17);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Los Primos', 'OTRO' ,17);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora La Curvita', 'OTRO' ,18);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Prado Azul', 'OTRO' ,18);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Los Valles', 'OTRO' ,19);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora La Casa de Maíta', 'OTRO' ,19);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'El Sueño', 'OTRO' ,20);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Distribuidora Te Lo Armo', 'OTRO' ,20);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora Bahías', 'OTRO' ,21);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora La Churuata', 'OTRO' ,21);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Comercializadora No Te Estreses', 'OTRO' ,22);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Así De Fácil', 'OTRO' ,22);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Mayoristas El Rincón De Sarah', 'OTRO' ,23);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Catering Venezuela', 'ALIMENTOS' ,23);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Marisol 2', 'OTRO' ,24);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Asociación Los Fernández', 'OTRO' ,24);

#floristerias
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'El jardín de la nena' , 'FLORES', 1);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Marisol' , 'FLORES', 2);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Arreglos Rosa María' , 'FLORES', 3);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Flores Capital' , 'FLORES', 4);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Rodríguez' , 'FLORES', 5);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Rosas negras' , 'FLORES', 6);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Lirio del valle' , 'FLORES', 7);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Echale agua' , 'FLORES', 8);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Jardín místico' , 'FLORES', 9);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Hiedra Venenosa' , 'FLORES', 10);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Las flores de Ivy' , 'FLORES', 11);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Ciudad Gótica' , 'FLORES', 12);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Las rosas de Martha' , 'FLORES', 13);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Súper arreglos' , 'FLORES', 14);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Tú arreglo floral' , 'FLORES', 15);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Doña Tita' , 'FLORES', 16);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Las 3 Rosas' , 'FLORES', 17);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Los crisántemos' , 'FLORES', 18);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Flor para llevar' , 'FLORES', 19);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Semilla de amapola' , 'FLORES', 20);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'La gran orquídea' , 'FLORES', 21);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Jardín del edén' , 'FLORES', 22);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Mi jardín' , 'FLORES', 23);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, tipo_proveedor, fk_lugar) value (null, 'Floristería Fruto prohibido' , 'FLORES', 24);

select count(*) from proveedor where tipo_proveedor = 'FLORES';