insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765334, 'Liam', 'Smith', 'LiamSmith6@gmail.com', 391);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765335, 'Noah', 'Johnson', 'NoahJohnson2@gmail.com', 392);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765336, 'William', 'Williams', 'null', 393);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765337, 'James', 'Brown', 'JamesBrown6@yahoo.com', 394);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765338, 'Oliver', 'Jones', 'null', 382);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765339, 'Emma', 'Garcia', 'EmmaGarcia6@gmail.com', 383);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765340, 'Olivia', 'Miller', 'null', 384);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765341, 'Ava', 'Davis', 'null', 385);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765342, 'Isabella', 'Rodriguez', 'IsabellaRodriguez8@yahoo.com', 386);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765343, 'Sophia', 'Martinez', 'null', 387);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765344, 'Benjamin', 'Hernandez', 'BenjaminHernandez8@yahoo.com', 411);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765345, 'Elijah', 'Lopez', 'null', 411);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765346, 'Lucas', 'Gonzalez', 'LucasGonzalez6@yahoo.com', 411);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765347, 'Mason', 'Wilson', 'null', 412);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765348, 'Logan', 'Anderson', 'LoganAnderson4@yahoo.com', 413);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765349, 'Mia', 'Thomas', 'null', 414);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765350, 'Amelia', 'Taylor', 'null', 415);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765351, 'Harper', 'Moore', 'null', 416);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765352, 'Evelyn', 'Jackson', 'EvelynJackson2@yahoo.com', 417);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765353, 'Abigail', 'Martin', 'null', 418);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765354, 'Alexander', 'Lee', 'null', 469);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765355, 'Ethan', 'Perez', 'null', 469);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765356, 'Jacob', 'Thompson', 'null', 470);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765357, 'Michael', 'White', 'MichaelWhite2@gmail.com', 471);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765358, 'Daniel', 'Harris', 'DanielHarris8@yahoo.com', 472);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765359, 'Charlotte', 'Sanchez', 'null', 473);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765360, 'Emily', 'Clark', 'null', 474);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765361, 'Elizabeth', 'Ramirez', 'null', 475);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765362, 'Mila', 'Lewis', 'null', 476);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765363, 'Ella', 'Robinson', 'null', 477);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765364, 'Henry', 'Walker', 'null', 495);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765365, 'Jackson', 'Young', 'JacksonYoung8@yahoo.com', 496);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765366, 'Sebastian', 'Allen', 'null', 497);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765367, 'Aiden', 'King', 'null', 498);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765368, 'Matthew', 'Wright', 'null', 498);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765369, 'Avery', 'Scott', 'AveryScott8@gmail.com', 499);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765370, 'Sofia', 'Torres', 'SofiaTorres8@yahoo.com', 500);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765371, 'Camila', 'Nguyen', 'null', 501);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765372, 'Aria', 'Hill', 'AriaHill6@yahoo.com', 502);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765373, 'Scarlett', 'Flores', 'ScarlettFlores4@yahoo.com', 503);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765374, 'Samuel', 'Green', 'null', 546);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765375, 'David', 'Adams', 'DavidAdams2@gmail.com', 546);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765376, 'Joseph', 'Nelson', 'null', 547);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765377, 'Carter', 'Baker', 'CarterBaker8@yahoo.com', 548);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765378, 'Owen', 'Hall', 'OwenHall4@yahoo.com', 549);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765379, 'Victoria', 'Rivera', 'null', 550);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765380, 'Madison', 'Campbell', 'MadisonCampbell6@gmail.com', 551);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765381, 'Luna', 'Mitchell', 'null', 552);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765382, 'Grace', 'Carter', 'null', 553);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765383, 'Chloe', 'Roberts', 'ChloeRoberts4@yahoo.com', 554);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765384, 'Wyatt', 'Gomez', 'null', 600);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765385, 'John', 'Phillips', 'null', 600);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765386, 'Jack', 'Evans', 'null', 601);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765387, 'Luke', 'Turner', 'null', 602);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765388, 'Jayden', 'Diaz', 'JaydenDiaz6@yahoo.com', 603);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765389, 'Penelope', 'Parker', 'null', 604);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765390, 'Layla', 'Cruz', 'null', 605);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765391, 'Riley', 'Edwards', 'null', 606);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765392, 'Zoey', 'Collins', 'ZoeyCollins8@gmail.com', 607);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765393, 'Nora', 'Reyes', 'null', 608);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765394, 'Dylan', 'Stewart', 'DylanStewart6@yahoo.com', 648);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765395, 'Grayson', 'Morris', 'null', 649);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765396, 'Levi', 'Morales', 'null', 650);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765397, 'Isaac', 'Murphy', 'IsaacMurphy4@gmail.com', 651);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765398, 'Gabriel', 'Cook', 'null', 652);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765399, 'Lily', 'Rogers', 'null', 653);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765400, 'Eleanor', 'Gutierrez', 'null', 654);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765401, 'Hannah', 'Ortiz', 'null', 655);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765402, 'Lillian', 'Morgan', 'null', 656);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765403, 'Addison', 'Cooper', 'AddisonCooper6@gmail.com', 657);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765404, 'Julian', 'Peterson', 'null', 685);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765405, 'Mateo', 'Bailey', 'null', 686);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765406, 'Anthony', 'Reed', 'null', 696);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765407, 'Jaxon', 'Kelly', 'null', 697);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765408, 'Lincoln', 'Howard', 'null', 698);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765409, 'Aubrey', 'Ramos', 'null', 689);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765410, 'Ellie', 'Kim', 'EllieKim4@gmail.com', 690);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765411, 'Stella', 'Cox', 'StellaCox2@yahoo.com', 691);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765412, 'Natalie', 'Ward', 'null', 692);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765413, 'Zoe', 'Richardson', 'null', 687);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765414, 'Joshua', 'Watson', 'JoshuaWatson6@yahoo.com', 700);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765415, 'Christopher', 'Brooks', 'null', 701);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765416, 'Andrew', 'Chavez', 'null', 702);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765417, 'Theodore', 'Wood', 'null', 700);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765418, 'Caleb', 'James', 'CalebJames4@yahoo.com', 703);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765419, 'Leah', 'Bennett', 'null', 704);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765420, 'Hazel', 'Gray', 'null', 705);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765421, 'Violet', 'Mendoza', 'VioletMendoza2@yahoo.com', 706);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765422, 'Aurora', 'Ruiz', 'null', 707);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765423, 'Savannah', 'Hughes', 'SavannahHughes4@gmail.com', 708);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765424, 'Ozzy', 'Price', 'null', 360);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765425, 'Lars', 'Alvarez', 'LarsAlvarez8@gmail.com', 361);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765426, 'Corey', 'Castillo', 'null', 362);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765427, 'Harry', 'Sanders', 'HarrySanders4@yahoo.com', 363);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765428, 'Brandon', 'Patel', 'BrandonPatel8@yahoo.com', 364);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765429, 'Janis', 'Myers', 'null', 365);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765430, 'Natasha', 'Long', 'null', 366);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765431, 'Ella', 'Ross', 'null', 367);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765432, 'Luna', 'Foster', 'LunaFoster6@gmail.com', 368);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765433, 'Barbara', 'Jimenez', 'null', 369);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765434, 'Isaiah', 'Powell', 'IsaiahPowell4@gmail.com', 720);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765435, 'Charles', 'Jenkins', 'CharlesJenkins4@yahoo.com', 721);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765436, 'Josiah', 'Perry', 'null', 722);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765437, 'Hudson', 'Russell', 'null', 723);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765438, 'Christian', 'Sullivan', 'null', 724);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765439, 'Lucy', 'Bell', 'LucyBell2@gmail.com', 725);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765440, 'Paisley', 'Coleman', 'null', 726);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765441, 'Everly', 'Butler', 'null', 727);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765442, 'Anna', 'Henderson', 'AnnaHenderson8@yahoo.com', 728);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765443, 'Caroline', 'Barnes', 'null', 729);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765444, 'Hunter', 'Gonzales', 'null', 804);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765445, 'Connor', 'Fisher', 'null', 805);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765446, 'Eli', 'Vasquez', 'EliVasquez8@gmail.com', 806);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765447, 'Ezra', 'Simmons', 'null', 807);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765448, 'Aaron', 'Romero', 'null', 808);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765449, 'Nova', 'Jordan', 'null', 809);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765450, 'Genesis', 'Patterson', 'null', 810);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765451, 'Emilia', 'Alexander', 'EmiliaAlexander6@yahoo.com', 811);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765452, 'Kennedy', 'Hamilton', 'KennedyHamilton6@yahoo.com', 812);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765453, 'Samantha', 'Graham', 'SamanthaGraham8@gmail.com', 813);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765454, 'Landon', 'Reynolds', 'null', 1364);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765455, 'Adrian', 'Griffin', 'AdrianGriffin6@yahoo.com', 1365);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765456, 'Jonathan', 'Wallace', 'JonathanWallace4@yahoo.com', 1366);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765457, 'Nolan', 'Moreno', 'NolanMoreno6@yahoo.com', 1367);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765458, 'Jeremiah', 'West', 'null', 1368);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765459, 'Maya', 'Cole', 'null', 1369);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765460, 'Willow', 'Hayes', 'WillowHayes8@gmail.com', 1370);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765461, 'Kinsley', 'Bryant', 'null', 1371);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765462, 'Naomi', 'Herrera', 'null', 1372);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765463, 'Aaliyah', 'Gibson', 'null', 1373);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765464, 'Easton', 'Ellis', 'null', 843);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765465, 'Elias', 'Tran', 'EliasTran4@yahoo.com', 844);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765466, 'Colton', 'Medina', 'null', 845);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765467, 'Cameron', 'Aguilar', 'CameronAguilar8@gmail.com', 846);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765468, 'Carson', 'Stevens', 'CarsonStevens4@yahoo.com', 847);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765469, 'Elena', 'Murray', 'null', 848);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765470, 'Sarah', 'Ford', 'SarahFord6@yahoo.com', 849);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765471, 'Ariana', 'Castro', 'null', 850);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765472, 'Allison', 'Marshall', 'AllisonMarshall6@yahoo.com', 851);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765473, 'Gabriella', 'Owens', 'GabriellaOwens4@gmail.com', 852);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765474, 'Robert', 'Harrison', 'null', 901);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765475, 'Angel', 'Fernandez', 'null', 902);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765476, 'Maverick', 'Mcdonald', 'MaverickMcdonald8@gmail.com', 903);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765477, 'Nicholas', 'Woods', 'NicholasWoods4@yahoo.com', 904);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765478, 'Dominic', 'Washington', 'null', 905);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765479, 'Alice', 'Kennedy', 'null', 906);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765480, 'Madelyn', 'Wells', 'MadelynWells4@gmail.com', 907);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765481, 'Cora', 'Vargas', 'CoraVargas4@gmail.com', 908);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765482, 'Ruby', 'Henry', 'null', 909);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765483, 'Eva', 'Chen', 'EvaChen2@yahoo.com', 910);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765484, 'Jaxson', 'Freeman', 'JaxsonFreeman2@yahoo.com', 987);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765485, 'Greyson', 'Webb', 'null', 988);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765486, 'Adam', 'Tucker', 'null', 989);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765487, 'Ian', 'Guzman', 'null', 990);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765488, 'Austin', 'Burns', 'AustinBurns8@gmail.com', 991);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765489, 'Serenity', 'Crawford', 'null', 992);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765490, 'Autumn', 'Olson', 'null', 993);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765491, 'Adeline', 'Simpson', 'null', 994);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765492, 'Hailey', 'Porter', 'HaileyPorter6@yahoo.com', 995);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765493, 'Gianna', 'Hunter', 'null', 996);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765494, 'Santiago', 'Gordon', 'SantiagoGordon2@gmail.com', 1041);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765495, 'Jordan', 'Mendez', 'JordanMendez2@gmail.com', 1042);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765496, 'Cooper', 'Silva', 'null', 1043);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765497, 'Brayden', 'Shaw', 'BraydenShaw2@gmail.com', 1044);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765498, 'Roman', 'Snyder', 'null', 1045);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765499, 'Valentina', 'Mason', 'null', 1046);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765500, 'Isla', 'Dixon', 'IslaDixon4@yahoo.com', 1047);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765501, 'Eliana', 'Munoz', 'null', 1048);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765502, 'Quinn', 'Hunt', 'null', 1049);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765503, 'Nevaeh', 'Hicks', 'NevaehHicks2@gmail.com', 1050);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765504, 'Evan', 'Holmes', 'null', 1085);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765505, 'Ezekiel', 'Palmer', 'EzekielPalmer6@yahoo.com', 1086);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765506, 'Xavier', 'Wagner', 'XavierWagner8@yahoo.com', 1087);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765507, 'Jose', 'Black', 'JoseBlack8@gmail.com', 1088);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765508, 'Jace', 'Robertson', 'JaceRobertson2@yahoo.com', 1089);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765509, 'Ivy', 'Boyd', 'IvyBoyd2@gmail.com', 1090);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765510, 'Sadie', 'Rose', 'SadieRose2@yahoo.com', 1091);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765511, 'Piper', 'Stone', 'PiperStone6@yahoo.com', 1092);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765512, 'Lydia', 'Salazar', 'null', 1093);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765513, 'Alexa', 'Fox', 'null', 1094);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765514, 'Jameson', 'Warren', 'null', 1107);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765515, 'Leonardo', 'Mills', 'null', 1108);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765516, 'Bryson', 'Meyer', 'BrysonMeyer2@gmail.com', 1109);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765517, 'Axel', 'Rice', 'AxelRice6@yahoo.com', 1110);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765518, 'Everett', 'Schmidt', 'EverettSchmidt2@gmail.com', 1111);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765519, 'Josephine', 'Garza', 'JosephineGarza2@yahoo.com', 1112);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765520, 'Emery', 'Daniels', 'EmeryDaniels8@yahoo.com', 1113);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765521, 'Julia', 'Ferguson', 'JuliaFerguson4@gmail.com', 1114);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765522, 'Delilah', 'Nichols', 'null', 1115);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765523, 'Arianna', 'Stephens', 'AriannaStephens2@gmail.com', 1116);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765524, 'Parker', 'Soto', 'null', 1148);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765525, 'Kayden', 'Weaver', 'null', 1149);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765526, 'Miles', 'Ryan', 'MilesRyan2@gmail.com', 1150);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765527, 'Sawyer', 'Gardner', 'SawyerGardner6@gmail.com', 1151);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765528, 'Jason', 'Payne', 'null', 1152);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765529, 'Vivian', 'Grant', 'VivianGrant8@gmail.com', 1153);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765530, 'Kaylee', 'Dunn', 'null', 1154);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765531, 'Sophie', 'Kelley', 'SophieKelley8@yahoo.com', 1155);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765532, 'Brielle', 'Spencer', 'null', 1156);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765533, 'Madeline', 'Hawkins', 'null', 1157);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765534, 'Declan', 'Arnold', 'DeclanArnold8@yahoo.com', 1207);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765535, 'Weston', 'Pierce', 'null', 1208);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765536, 'Micah', 'Vazquez', 'MicahVazquez4@yahoo.com', 1209);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765537, 'Ayden', 'Hansen', 'null', 1210);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765538, 'Wesley', 'Peters', 'WesleyPeters2@yahoo.com', 1211);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765539, 'Peyton', 'Santos', 'null', 1212);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765540, 'Rylee', 'Hart', 'RyleeHart8@gmail.com', 1213);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765541, 'Clara', 'Bradley', 'null', 1214);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765542, 'Hadley', 'Knight', 'HadleyKnight2@yahoo.com', 1215);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765543, 'Melanie', 'Elliott', 'MelanieElliott6@gmail.com', 1216);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765544, 'Luca', 'Cunningham', 'LucaCunningham2@yahoo.com', 1271);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765545, 'Vincent', 'Duncan', 'null', 1272);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765546, 'Damian', 'Armstrong', 'DamianArmstrong4@gmail.com', 1273);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765547, 'Zachary', 'Hudson', 'null', 1274);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765548, 'Silas', 'Carroll', 'null', 1275);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765549, 'Mackenzie', 'Lane', 'null', 1276);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765550, 'Reagan', 'Riley', 'null', 1277);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765551, 'Adalynn', 'Andrews', 'null', 1278);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765552, 'Liliana', 'Alvarado', 'null', 1279);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765553, 'Aubree', 'Ray', 'null', 1280);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765554, 'Gavin', 'Delgado', 'null', 1375);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765555, 'Chase', 'Berry', 'null', 1389);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765556, 'Kai', 'Perkins', 'null', 1390);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765557, 'Emmett', 'Hoffman', 'null', 1391);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765558, 'Harrison', 'Johnston', 'null', 1376);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765559, 'Jade', 'Matthews', 'JadeMatthews4@gmail.com', 1377);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765560, 'Katherine', 'Pena', 'KatherinePena4@yahoo.com', 1378);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765561, 'Isabelle', 'Richards', 'IsabelleRichards4@yahoo.com', 1379);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765562, 'Natalia', 'Contreras', 'NataliaContreras8@gmail.com', 1380);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765563, 'Raelynn', 'Willis', 'null', 1380);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765564, 'Nathaniel', 'Carpenter', 'NathanielCarpenter6@gmail.com', 1452);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765565, 'Kingston', 'Lawrence', 'null', 1453);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765566, 'Cole', 'Sandoval', 'ColeSandoval6@gmail.com', 1454);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765567, 'Tyler', 'Guerrero', 'null', 1455);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765568, 'Bennett', 'George', 'BennettGeorge6@gmail.com', 1456);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765569, 'Maria', 'Chapman', 'MariaChapman6@yahoo.com', 1457);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765570, 'Athena', 'Rios', 'AthenaRios8@yahoo.com', 1458);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765571, 'Ximena', 'Estrada', 'null', 1459);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765572, 'Arya', 'Ortega', 'AryaOrtega8@yahoo.com', 1460);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (25765573, 'Leilani', 'Watkins', 'LeilaniWatkins6@yahoo.com', 1461);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780890, 'Asdruval', 'Perez', 'asdruvalperez5@yahoo.com', 368);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780891, 'Arisobulo', 'Gonzalez', 'aristobulogonzalez5@yahoo.com', 382);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780892, 'Delcys', 'Navarra', 'delcysn5@yahoo.com', 415);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780893, 'Daniel', 'Zamora', 'danielzamora5@yahoo.com', 484);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780894, 'Agustin', 'Soto', 'agustinsoto313@yahoo.com', 519);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780895, 'Erika', 'Farias', 'erikafarias80@yahoo.com', 578);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780896, 'Asdruval', 'Chavez', 'asdruvalchaves45@yahoo.com', 600);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780897, 'Hugo', 'Sanchez', 'hugosanz=chez@yahoo.com', 676);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780898, 'Wilker', 'Perez', 'wilkerperez5@yahoo.com', 699);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780899, 'Leonardo', 'Chirinos', 'leochirinos23@yahoo.com', 719);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780900, 'Elsan', 'Guchito', 'elsanguchito@yahoo.com', 789);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780901, 'Elsa', 'patito', 'elsapatitos@yahoo.com', 823);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780902, 'Alan', 'Brito', 'alanbritogonzales@yahoo.com', 852);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780903, 'Nicolas', 'Perez', 'nicoperez5@yahoo.com', 901);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780904, 'Franco', 'Cumares', 'francocumares@yahoo.com', 997);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780905, 'Diego', 'Gavidia', 'diegogavidia@yahoo.com', 1055);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780906, 'Armando', 'Paredes', 'armandoparedes@yahoo.com', 1085);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780907, 'Cecilio', 'Perez', 'cecilioperez5@yahoo.com', 1110);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780908, 'Astrid', 'Nieves', 'astridnieves@yahoo.com', 1183);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780909, 'Cesar', 'Gonzales', 'cesargonza@yahoo.com', 1258);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780910, 'Cornelio', 'Perez', 'cornelioperez@yahoo.com', 1351);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780911, 'Francisco', 'Franco', 'franciscofranco@yahoo.com', 1371);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780912, 'Cesar', 'Soto', 'sotocesar@yahoo.com', 1388);
insert into PERSONA(cedula_persona, nombre_persona, apellido_persona, correo_persona, fk_lugar) value (27780913, 'Daniel', 'Perez', 'danielperez@yahoo.com', 1453);

select l.id_lugar as i_parr, l.nombre_lugar as parroquia, l2.nombre_lugar as estado from lugar l, lugar l2, lugar l3 where l.fk_lugar = l3.id_lugar and l3.fk_lugar = l2.id_lugar order by l2.nombre_lugar;
#usuarios
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LiamSmit9', 'Kicker88$$', 25765334);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NoaJohn7', 'Kicker88$$', 25765335);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'WillWil5', 'Kicker88$$', 25765336);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JameBrow1', 'Kicker88$$', 25765337);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'OliJone6', 'Kicker88$$', 25765338);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EmmGar5', 'Kicker88$$', 25765339);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'OliMil2', 'Kicker88$$', 25765340);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AvaDav5', 'Kicker88$$', 25765341);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IsabRodr6', 'Kicker88$$', 25765342);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SophMart2', 'Kicker88$$', 25765343);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BenHern4', 'Kicker88$$', 25765344);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EliLope7', 'Kicker88$$', 25765345);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LucGon8', 'Kicker88$$', 25765346);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MasoWil3', 'Kicker88$$', 25765347);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LogAnd1', 'Kicker88$$', 25765348);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MiaTho6', 'Kicker88$$', 25765349);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AmeTay9', 'Kicker88$$', 25765350);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HarpMoor1', 'Kicker88$$', 25765351);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EveJac3', 'Kicker88$$', 25765352);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AbigMart8', 'Kicker88$$', 25765353);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AlexLee4', 'Kicker88$$', 25765354);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EthaPere4', 'Kicker88$$', 25765355);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JacThom7', 'Kicker88$$', 25765356);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MicWhi2', 'Kicker88$$', 25765357);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DanHarr5', 'Kicker88$$', 25765358);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChaSan8', 'Kicker88$$', 25765359);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EmiClar8', 'Kicker88$$', 25765360);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EliRami9', 'Kicker88$$', 25765361);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MilLew5', 'Kicker88$$', 25765362);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EllRobi7', 'Kicker88$$', 25765363);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HenWal3', 'Kicker88$$', 25765364);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JacYoun2', 'Kicker88$$', 25765365);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SebaAlle9', 'Kicker88$$', 25765366);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AideKin5', 'Kicker88$$', 25765367);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MatWrig2', 'Kicker88$$', 25765368);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AverSco6', 'Kicker88$$', 25765369);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SofTor8', 'Kicker88$$', 25765370);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CamiNguy2', 'Kicker88$$', 25765371);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AriaHill2', 'Kicker88$$', 25765372);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ScarFlo9', 'Kicker88$$', 25765373);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SamGre7', 'Kicker88$$', 25765374);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DaviAda1', 'Kicker88$$', 25765375);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JoseNel8', 'Kicker88$$', 25765376);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CarBake5', 'Kicker88$$', 25765377);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'OweHal9', 'Kicker88$$', 25765378);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'VicRive1', 'Kicker88$$', 25765379);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MadiCamp1', 'Kicker88$$', 25765380);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LunMitc7', 'Kicker88$$', 25765381);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GracCar5', 'Kicker88$$', 25765382);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChloRobe5', 'Kicker88$$', 25765383);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'WyatGom1', 'Kicker88$$', 25765384);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JohnPhil9', 'Kicker88$$', 25765385);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JacEvan6', 'Kicker88$$', 25765386);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LukeTurn9', 'Kicker88$$', 25765387);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JayDiaz3', 'Kicker88$$', 25765388);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'PenePark2', 'Kicker88$$', 25765389);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LayCruz5', 'Kicker88$$', 25765390);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RileEdw5', 'Kicker88$$', 25765391);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ZoeyColl1', 'Kicker88$$', 25765392);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NoraRey4', 'Kicker88$$', 25765393);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DylSte8', 'Kicker88$$', 25765394);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GrayMor6', 'Kicker88$$', 25765395);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LeviMor8', 'Kicker88$$', 25765396);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IsaaMur9', 'Kicker88$$', 25765397);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GabCook7', 'Kicker88$$', 25765398);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LilRoge9', 'Kicker88$$', 25765399);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EleaGut3', 'Kicker88$$', 25765400);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HanOrt2', 'Kicker88$$', 25765401);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LillMorg5', 'Kicker88$$', 25765402);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AddCoo1', 'Kicker88$$', 25765403);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JuliPete1', 'Kicker88$$', 25765404);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MateBai8', 'Kicker88$$', 25765405);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AnthRee9', 'Kicker88$$', 25765406);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JaxoKell4', 'Kicker88$$', 25765407);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LincHowa1', 'Kicker88$$', 25765408);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AubRam2', 'Kicker88$$', 25765409);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ElliKim4', 'Kicker88$$', 25765410);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SteCox6', 'Kicker88$$', 25765411);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NatWard4', 'Kicker88$$', 25765412);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ZoeRich3', 'Kicker88$$', 25765413);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JosWats8', 'Kicker88$$', 25765414);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChrBro8', 'Kicker88$$', 25765415);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AndrChav7', 'Kicker88$$', 25765416);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'TheoWood9', 'Kicker88$$', 25765417);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CalJam6', 'Kicker88$$', 25765418);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LeaBen6', 'Kicker88$$', 25765419);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HazGra9', 'Kicker88$$', 25765420);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ViolMen4', 'Kicker88$$', 25765421);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AurRui3', 'Kicker88$$', 25765422);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SavHug3', 'Kicker88$$', 25765423);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'OzzyPric8', 'Kicker88$$', 25765424);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LarsAlva4', 'Kicker88$$', 25765425);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CoreCast3', 'Kicker88$$', 25765426);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HarrSand4', 'Kicker88$$', 25765427);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BraPat3', 'Kicker88$$', 25765428);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JanMyer4', 'Kicker88$$', 25765429);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NatLon2', 'Kicker88$$', 25765430);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EllRoss8', 'Kicker88$$', 25765431);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LunFos2', 'Kicker88$$', 25765432);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BarJim8', 'Kicker88$$', 25765433);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IsaPow3', 'Kicker88$$', 25765434);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChaJenk5', 'Kicker88$$', 25765435);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JosiPerr1', 'Kicker88$$', 25765436);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HudRus7', 'Kicker88$$', 25765437);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChrSul3', 'Kicker88$$', 25765438);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LucBell1', 'Kicker88$$', 25765439);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'PaiCole1', 'Kicker88$$', 25765440);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EveButl3', 'Kicker88$$', 25765441);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AnnaHen6', 'Kicker88$$', 25765442);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CarBarn2', 'Kicker88$$', 25765443);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HuntGon5', 'Kicker88$$', 25765444);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ConnFish9', 'Kicker88$$', 25765445);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EliVasq5', 'Kicker88$$', 25765446);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EzraSimm3', 'Kicker88$$', 25765447);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AarRome4', 'Kicker88$$', 25765448);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NovaJor3', 'Kicker88$$', 25765449);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GenPatt8', 'Kicker88$$', 25765450);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EmiAlex9', 'Kicker88$$', 25765451);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KennHam9', 'Kicker88$$', 25765452);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SamGra2', 'Kicker88$$', 25765453);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LanReyn7', 'Kicker88$$', 25765454);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AdrGri1', 'Kicker88$$', 25765455);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JonaWall7', 'Kicker88$$', 25765456);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NolaMor6', 'Kicker88$$', 25765457);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JereWest6', 'Kicker88$$', 25765458);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MayCol4', 'Kicker88$$', 25765459);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'WilHaye7', 'Kicker88$$', 25765460);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KinBry4', 'Kicker88$$', 25765461);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NaoHer3', 'Kicker88$$', 25765462);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AalGibs8', 'Kicker88$$', 25765463);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EastElli1', 'Kicker88$$', 25765464);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EliaTra4', 'Kicker88$$', 25765465);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ColMedi4', 'Kicker88$$', 25765466);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CamAgui1', 'Kicker88$$', 25765467);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CarStev1', 'Kicker88$$', 25765468);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EleMurr5', 'Kicker88$$', 25765469);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SaraFord1', 'Kicker88$$', 25765470);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AriaCast3', 'Kicker88$$', 25765471);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AlliMars2', 'Kicker88$$', 25765472);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GabOwen8', 'Kicker88$$', 25765473);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RobHar4', 'Kicker88$$', 25765474);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AngFern5', 'Kicker88$$', 25765475);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MaveMcd9', 'Kicker88$$', 25765476);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NichWood7', 'Kicker88$$', 25765477);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DomiWash3', 'Kicker88$$', 25765478);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AlicKen9', 'Kicker88$$', 25765479);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MadeWell7', 'Kicker88$$', 25765480);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CoraVar7', 'Kicker88$$', 25765481);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RubyHen9', 'Kicker88$$', 25765482);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EvaChe9', 'Kicker88$$', 25765483);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JaxsFree8', 'Kicker88$$', 25765484);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GreWebb3', 'Kicker88$$', 25765485);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AdaTuck7', 'Kicker88$$', 25765486);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IanGuz2', 'Kicker88$$', 25765487);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AusBur1', 'Kicker88$$', 25765488);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SereCraw6', 'Kicker88$$', 25765489);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AutOls6', 'Kicker88$$', 25765490);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AdelSimp6', 'Kicker88$$', 25765491);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HaiPor7', 'Kicker88$$', 25765492);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GianHun8', 'Kicker88$$', 25765493);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SanGord6', 'Kicker88$$', 25765494);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JordMend3', 'Kicker88$$', 25765495);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'CoopSil8', 'Kicker88$$', 25765496);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BraySha4', 'Kicker88$$', 25765497);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RomaSny6', 'Kicker88$$', 25765498);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ValeMas2', 'Kicker88$$', 25765499);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IslaDix2', 'Kicker88$$', 25765500);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EliaMun3', 'Kicker88$$', 25765501);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'QuiHun4', 'Kicker88$$', 25765502);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NevaHick9', 'Kicker88$$', 25765503);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EvanHol4', 'Kicker88$$', 25765504);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EzePal7', 'Kicker88$$', 25765505);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'XaviWagn3', 'Kicker88$$', 25765506);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JoseBlac3', 'Kicker88$$', 25765507);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JaceRobe5', 'Kicker88$$', 25765508);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IvyBoy1', 'Kicker88$$', 25765509);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SadRos6', 'Kicker88$$', 25765510);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'PipeSto3', 'Kicker88$$', 25765511);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LydiSala2', 'Kicker88$$', 25765512);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AlexFox5', 'Kicker88$$', 25765513);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JamWarr5', 'Kicker88$$', 25765514);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LeonMil3', 'Kicker88$$', 25765515);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BryMeye2', 'Kicker88$$', 25765516);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AxeRice3', 'Kicker88$$', 25765517);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EverSch1', 'Kicker88$$', 25765518);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JosGarz2', 'Kicker88$$', 25765519);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EmeDan1', 'Kicker88$$', 25765520);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JuliFer8', 'Kicker88$$', 25765521);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DelNic7', 'Kicker88$$', 25765522);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AriaStep6', 'Kicker88$$', 25765523);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ParkSoto5', 'Kicker88$$', 25765524);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KayWea1', 'Kicker88$$', 25765525);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MilRyan1', 'Kicker88$$', 25765526);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SawyGard1', 'Kicker88$$', 25765527);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JasoPayn3', 'Kicker88$$', 25765528);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'VivGran4', 'Kicker88$$', 25765529);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KayDun6', 'Kicker88$$', 25765530);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SopKel9', 'Kicker88$$', 25765531);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BriSpen8', 'Kicker88$$', 25765532);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MadHawk2', 'Kicker88$$', 25765533);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DecArno8', 'Kicker88$$', 25765534);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'WesPie7', 'Kicker88$$', 25765535);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MicaVazq5', 'Kicker88$$', 25765536);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AydeHan2', 'Kicker88$$', 25765537);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'WesPet3', 'Kicker88$$', 25765538);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'PeySant1', 'Kicker88$$', 25765539);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RylHar9', 'Kicker88$$', 25765540);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ClarBrad5', 'Kicker88$$', 25765541);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HadlKnig4', 'Kicker88$$', 25765542);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MelaElli5', 'Kicker88$$', 25765543);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LucaCun3', 'Kicker88$$', 25765544);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'VincDunc9', 'Kicker88$$', 25765545);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'DamiArms9', 'Kicker88$$', 25765546);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ZachHud8', 'Kicker88$$', 25765547);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'SilCarr7', 'Kicker88$$', 25765548);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MackLane2', 'Kicker88$$', 25765549);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ReaRil7', 'Kicker88$$', 25765550);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AdaAnd8', 'Kicker88$$', 25765551);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LilAlv1', 'Kicker88$$', 25765552);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AubrRay2', 'Kicker88$$', 25765553);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'GaviDel5', 'Kicker88$$', 25765554);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ChasBerr8', 'Kicker88$$', 25765555);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KaiPer8', 'Kicker88$$', 25765556);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'EmmHof1', 'Kicker88$$', 25765557);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'HarrJoh9', 'Kicker88$$', 25765558);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'JadMat6', 'Kicker88$$', 25765559);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KathPena4', 'Kicker88$$', 25765560);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'IsaRich6', 'Kicker88$$', 25765561);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NataCont4', 'Kicker88$$', 25765562);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'RaeWill4', 'Kicker88$$', 25765563);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'NatCar3', 'Kicker88$$', 25765564);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'KingLaw3', 'Kicker88$$', 25765565);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'ColSan1', 'Kicker88$$', 25765566);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'TylGuer4', 'Kicker88$$', 25765567);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'BennGeo5', 'Kicker88$$', 25765568);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'MarChap3', 'Kicker88$$', 25765569);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AtheRios5', 'Kicker88$$', 25765570);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'XimEst5', 'Kicker88$$', 25765571);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'AryaOrte6', 'Kicker88$$', 25765572);
insert into USUARIO(id_usuario, nombre_usuario, passw_usuario, fk_persona) value (null, 'LeilWatk5', 'Kicker88$$', 25765573);

select p.nombre_persona, p.apellido_persona, l.nombre_lugar from PERSONA p, LUGAR l where p.fk_lugar = l.id_lugar;
select count(p.nombre_persona), l.nombre_lugar from PERSONA p, LUGAR l, lugar l2, lugar l3 where p.fk_lugar = l3.id_lugar and l3.fk_lugar = l2.id_lugar and l2.fk_lugar = l.id_lugar group by l.nombre_lugar;
select u.nombre_usuario, p.nombre_persona, p.apellido_persona, p.correo_persona from usuario u, persona p where u.fk_persona=p.cedula_persona;
select count(u.nombre_usuario), p.nombre_persona from usuario u, persona p where u.fk_persona = p.cedula_persona group by p.nombre_persona;
select count(*) from usuario;
select l.id_lugar as i_parr, l.nombre_lugar as parroquia, l2.nombre_lugar as estado from lugar l, lugar l2, lugar l3 where l.fk_lugar = l3.id_lugar and l3.fk_lugar = l2.id_lugar and l2.id_lugar = 24 order by l2.nombre_lugar;
select p.fk_lugar, p.nombre_persona, l.nombre_lugar from persona p, lugar l, lugar l2, lugar l3 where p.fk_lugar = l3.id_lugar and l3.fk_lugar = l2.id_lugar and l2.fk_lugar = l.id_lugar;