insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Martinez' ,1);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Cargo Venezuela' ,1);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Brothers Company' ,2);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Tu Producto C.A.' ,2);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Te lo tengo VE' ,3);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Amigos y Familia inc.' ,3);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Precios Alfa' ,4);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Vete De Compras' ,4);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Resuelve' ,5);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'No Busques Más' ,5);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Master Festejos' ,6);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Don Obsequio' ,6);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Santo Remedio' ,7);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora A Tu Alcance C.A.' ,7);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Mar y Sol' ,8);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Doña Milly' ,8);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Parties International' ,9);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Sirvete Un Trago' ,9);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Ponle Hielo' ,10);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Moving Food' ,10);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Hasta El Final' ,11);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'El Último Chicharrón' ,11);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Mar y Tierra' ,12);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Damar' ,12);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Come Con Calma' ,13);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Te Lo LLevamos' ,13);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Tú Primero' ,14);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas La Victoria' ,14);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Los Chinos' ,15);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Dragón De Oro' ,15);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas Botellón' ,16);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'El Lugar De Las Telas' ,16);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Fabricantes Venezuela' ,17);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Los Primos' ,17);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora La Curvita' ,18);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Prado Azul' ,18);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Los Valles' ,19);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora La Casa de Maíta' ,19);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'El Sueño' ,20);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Distribuidora Te Lo Armo' ,20);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora Bahías' ,21);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora La Churuata' ,21);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Comercializadora No Te Estreses' ,22);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Así De Fácil' ,22);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Mayoristas El Rincón De Sarah' ,23);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Catering Venezuela' ,23);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Marisol 2' ,24);
insert into PROVEEDOR(id_proveedor, nombre_proveedor, fk_lugar) value (null, 'Asociación Los Fernández' ,24);

select * from proveedor;