#CATEGORIA
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Tarjeteria', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Accesorios', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Recuerdos', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Musica', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Comida', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Bebida', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mobiliario', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Utileria', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Flores', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Decoracion', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Entretenimiento', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Salones de Fiesta', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Fotografia', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Protocolo', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Transporte', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Otros', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Accesorios para novia', 2);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Accesorios para XV', 2);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Bandas', 4);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'DJ', 4);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Pianista', 4);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mariachis', 4);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mesas', 7);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Sillas', 7);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Bouquets', 10);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Boutonnieres', 10);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Vestidos', 10);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mobiliario de festejo', 7);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mobiliario Longue', 7);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Pasapalo', 5);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mini Dulces', 5);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Mobiliario de acrílico y cristal', 7);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Toldos, pistas, tarimas y baños', null);
insert into CATEGORIA(id_categoria, nombre_categoria, fk_categoria) value(null, 'Restaurantes', 12);