insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Invitaciones', 'En lugar de las clásicas invitaciones impresas, puedes preparar un bonito video de dos o tres minutos. Puede ser romántico, musical, divertido o en el estilo que más te guste, con fotos de ustedes y los datos de la fiesta. Resultará sorpresivo, económico y mucho más cálido que un sobre recibido por correo.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Vestido', 'No busques vestido de novia. En el momento en que mencionas vestido de novia, los precios suben. ¡Y por vestidos tremendamente similares! Si quieres ahorrar en tu vestido sin sacrificar tu look, busca vestidos en color blanco o marfil ¡o en el color que más desees! Hasta los diseñadores tienen precios más bajos cuando de vestidos se trata. Te sorprenderás de los exquisitos modelos que encontrarás.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Mesa', 'Mientras más grande la mesa, menor la cantidad de centros de mesa o decoración de mesa que se precisará. En lugar de mesas de seis personas, escoge las de 8.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Invitados', 'Si a la mayoría de tus invitados les gusta la parranda, su intensidad y volumen irán en aumento y gradualmente la fiesta es un descontrol. Del mismo modo, si los más callados no se sientan junto a invitados más animados, tu recepción será sumamente aburrida. Para lograr una recepción divertida y agradable intenta equilibrar ambas personalidades en las mesas.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Mesa Principal', 'La mesa principal debe colocarse donde la puedan ver el mayor número posible de invitados. Recuerda que ustedes son los protagonistas de esta celebración, y todos querrán verlos y tenerlos cerca.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Invitados jovenes', 'Sienta a los invitados más jóvenes cerca de los parlantes y de la pista de baile y a los invitados mayores un poco más lejos, así se sentirán más cómodos.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Recuerdos', 'A veces se nos olvida de que aquellos que asisten a la boda merecen ser atendidos de la mejor forma y nada mejor que dejar un recuerdo inolvidable en sus mentes por acompañarlos en uno de los días más importantes de sus vidas.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Luna de miel', '¿No saben cómo elegir destino para tu luna de miel?. Pues estamos seguros que siempre han soñado con algún lugar al cual ir y este es el mejor momento para conocerlo.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Número de invitados', 'Haz un cálculo aproximado de los invitados que quieres que asistan a tu boda antes de contratar el banquete. Esto asegurará que haya espacio suficiente para que se encuentren cómodos.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Lugar de celebración', 'Asegúrate de que los invitados estén bien informados del lugar de la ceremonia, es decir ubicación exacta, los horarios y el transporte.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Fotografo', 'Seguro que no quieres perderte ningún detalle del día de tu boda, por ello, es importante que cuentes con la presencia de un profesional de la fotografía, y que escojas según su estilo a la hora de inmortalizar cada momento.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Comida y bebida', 'Si se dan cuenta, cada evento especial se suele celebrar acompañándolo de bebidas deliciosas y de alimentos de calidad. Su boda no iba a ser diferente, haz que tus invitados la recuerden como una experiencia para los sentidos.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Detalle para invitados', 'Nada les dice a tus invitados que los conoces y son realmente importantes para ti como prepararles un detalle personalizado en sus mesas.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Música', 'La música ambienta, le da colorido a un evento y hace que los pies y los corazones recuerden, se muevan y se conmuevan. Tu selección de conjunto musical es muy importante pues uno bueno logrará ver a tus invitados, descubrir qué les gusta y hallar la melodía perfecta para cada momento de la boda, así que no olvides consultar y escuchar varias opciones antes de elegir uno.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Tarjetas de agradecimiento', 'Otro detalle increíble y de mucha personalidad que puedes tener con tus invitados es entregarles tarjetas de agradecimiento personalizadas. Tanto el mensaje como los diseños pueden variar ligeramente y eso las haría incluso más únicas y representativas del afecto que sientes por cada uno de ellos.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Día de la boda', 'Pensemos en el momento que todas ustedes vivirán: me refiero al instante en que despierten y piensen: “¡Hoy me caso!”. Para disfrutar la boda al máximo es importante que descansen bien, que pongan en práctica técnicas de relajación, no se desvelen y, por supuesto, que no lleguen a la boda con el estómago vacío.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Vestimenta', 'Para comenzar ese día con el pie derecho es importante que ambos novios se arreglen con tiempo para evitar contratiempos y prisas, que generarán estrés y mal humor.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Momentos previos a la boda', 'Cuando lleguen al lugar donde se celebrará la boda, busquen un momento para estar en privado, respiren hondo, caminen, muevan los brazos, griten… lo que les funcione para deshacerse de los nervios y la tensión.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Zapatos', 'Les aseguro que unos zapatos incómodos restarán diversión a la boda. Por nada del mundo elijan unos zapatos increíbles, pero igualmente incómodos. Asimismo, no olviden un cambio de zapatos para la hora de la fiesta y baile.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'BODA', 'Tiempo de pareja', 'Pasen tiempo juntos. No olviden que ustedes son la razón de la fiesta, así que concéntrense en disfrutar como pareja de su gran día y no se pierdan entre los amigos, amigas y compromisos.');

#quinces
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Tema', 'Elige un tema o motivo para consolidar la idea para tu fiesta de Quinceañera. Esto hará que planear una Quinceañera sea mucho más fácil.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Flores', 'Si tienes un color específico en mente, investiga cuáles flores están disponibles durante la temporada de tu fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Invitados mayores', 'Si piensas invitar a personas mayores a tu fiesta, asegúrate de que haya suficientes lugares para poder sentarse.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Restricciones en la comida', 'Recuerda que algunas personas tienen restricciones dietéticas como alergias. De ser posible, asegúrate de que el menú incluya algo que todos puedan comer.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Compatibilidad de invitados', 'Junta a personas con intereses similares y de la misma edad en la misma mesa. Asegúrate de que cada mesa tenga un número par de personas ya que los invitados tienden a platicar en pares. No quisieras dejar alguien fuera.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Agradecimientos', 'Las notas de agradecimiento son tan importantes como las invitaciones. El día después de tu Quinceañera es el momento perfecto para escribirlas, ya que tu memoria aún está fresca.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Tiempo de planificación', 'Es necesario que cuentes con bastante tiempo para planificar, así te ahorras estrés  y puedes reservar servicios con más tranquilidad.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Peinado y maquillaje', 'Visita expertos en Hair & Make-up y separa el que se ajuste a tu presupuesto y te guste como te arregló.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Colores', 'Escoge un color o un par de colores que te gusten especialmente y que no desentonen con la temática de la fiesta, un color que tenga algún significado especial para ti. Los puedes llevar en el vestido, en las guirnaldas que adornen el salón, las cortinas, el mantel, la vajilla... Combina como más te guste.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Usar rojo', 'El tono más audaz como el rojo se encuentran en un esquema elegante para aquellas que buscan un look más atrevido.');

#decoracion
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Pizarras de gis', 'Una idea para darle al evento un toque bohemio, artesanal y divertido es incluir la tendencia de imitar las pizarras y escribir mensajes con gis. Algo diferente que vale la pena intentar, aunque sea en algún detalle para tu fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Colores naranja y rosa', 'La combinacion de naranja y el rosa crearán un ambiente divertido en tu fiesta. ¡Incorpora centros de mesa con flores de colores vivos para animar el lugar!');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Flores tropicales', '¡Las flores tropicales y las tonalidades inspiradas en el océano le darán vida a tu fiesta!');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Accesorios básicos', 'Siempre se debe contar con los accesorios básicos; los globos y las serpentinas son elementales y nunca estarán de más en una fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Vajilla colorida', 'Elige platos, vasos, servilletas y cubiertos de papel en base a tu paleta de color.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Jerarquía en la mesa', 'Mantén un orden jerárquico en la mesa, ubicando los elementos protagonistas y más voluminosos en el centro y parte posterior, dejando los más pequeñitos en la parte frontal.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Fiest infantil', 'En caso de ser una fiesta infantil, es importante que la decoración sea adecuada a la edad de los invitados.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Banderines y guirnaldas', 'Personaliza tus propios banderines y guirnaldas para decorar tu fiestan Este tipo de elementos alegran cualquier evento, sobre todo cuando se trata de cumpleaños o fiestas de bienvenidas.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Luces', 'Las luces son un factor muy importante que no siempre se tiene en cuenta a la hora de preparar la decoración de una fiesta. Si disponemos de focos de distintos colores, podremos jugar con distintos efectos sobre globos u otros elementos.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Velas', 'Si la fiesta es para adultos, una posibilidad es optar por una decoración con velas. Este tipo de iluminación queda especialmente llamativa por la noche.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Telas', 'La decoración con telas, se ha convertido en una de las favoritas en las fiestas.Principalmente la decoración de telas se realiza en los techos, por lo que debemos utilizar telas no muy pesadas para no tener problemas y que su peso las tire.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Luces nocturnas', 'Las bolsas de luz, tiras y guirnaldas de luces quedarán preciosas al anochecer. Usalas para rodear columnas, decorar árboles y arbustos, disimular paredes feas o sosas, bordear caminos, iluminar rincones oscuros, decorar la parte trasera del bar o buffet... y llenarlo todas las mesas con destellos de velitas.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Carteles', 'Si quieres que nadie se pierda en ese día tan especial no dejes de señalizar colgando carteles en árboles, paredes, columnas etc.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Bebidas', 'Anima tu fiesta con un rincón de bebidas o Corner Bar. Selecciona entre nuestros productos todo lo que necesitas para decorarlo con mucho estilo.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Sillas y mesas', 'Viste las mesas y las sillas a juego, para un resultado uniforme y coherente que dará mucha calidez a tu evento.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Flores', '¡La belleza de las flores es insuperable! llena tu fiesta o evento de pétalos, flores flotantes, rosas adhesivas entre otras para engalanar tu celebración.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Banderines', 'La forma más popular de decorar tu fiesta es usando banderines de colores. ¡Cunden muchísimo!.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Tiras y colgantes', 'Decora tus paredes, puertas y techos con tiras y colgantes que le vayan a tu fiesta. Puedes usarlos en la entrada para crear expectación o en la sala para separar ambientes. También quedan perfectos como fondos de escaparates o de mesas de buffet.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Tonos pastel', 'Los colores más utilizados para decorar una fiesta de 15 años son las tonalidades pastel, colores claros o en todos rosados. Lo importante es que transmita delicadeza y frescura en el espacio. Deberá reflejar la jovialidad de la anfitriona y el resto de los invitados adolescentes.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'XV', 'Combinacion de colores', 'Todos los objetos que elijas para decorar el espacio deberán respetar la combinación de colores que hayas elegido. Jamás te limites a incorporar un solo color, ya que sobrecargarás el espacio y será molesto a la vista. Deberás combinar tu color principal con un color claro u oscuro para equilibrar los tonos en el espacio.');

#Recomendaciones
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'El pastel', 'El Pastel, es un elemento muy importante en cualquier celebración. No puede faltar en tan importante evento.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Invitaciones con anticipación', 'Enviar con tiempo las invitaciones. Los invitados agradecerán ese tiempo para prepararse, ahorrar y cómo no, reservar ese día.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Lista de cosas', 'lista todas las cosas que tienes que hacer para que no se te escape nada y para que no quede nada imprevisto para el último momento.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Día de la celebración', '¿Cuándo celebrar tu fiesta? Generalmente los viernes y sábados por la tarde noche son los mejores días para organizar una fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Clima', 'Aunque parezca una obviedad, la climatología puede fastidiarnos completamente un evento, así que esto debes tenerlo en cuenta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Decoración personalizada', 'La decoración personalizada va a jugar un papel fundamental en tu fiestas, así que no renuncies a ella y destina parte del presupuesto a personalizarla o tematizarla.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Espacio para invitados', 'En función del número de invitados, escoger un lugar en el que entren todos de forma cómoda.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Epoca de celebración', 'La época del año en la que organices la fiesta marcará completamente esta decisión. Si es en primavera o en verano, un lugar con espacios al aire libre resulta de lo más agradable.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Estacionamiento', 'Es importante que compruebes si el sitio cuenta con parking propio o tiene cercano un parking público o incluso servicio de aparcacoches. Es posible que muchos invitados opten por acudir al evento en su coche y si el estacionamiento no es fácil, puede suponer un problema.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Normas del Salón', 'Cuando escojas el espacio, asegúrate de preguntar primero lo que puedes y no puedes hacer.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Comida tipo coctel', 'Para una fiesta, lo ideal es que opten por un montaje tipo cóctel con aperitivos fáciles de comer. Este formato es más informal y permite a los invitados relacionarse entre ellos más libremente.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Puestos de comida', 'Los puestos de comida y los showcookings son una tendencia que está muy de moda y aportan originalidad y diversión al catering. El éxito está asegurado si los incluyes en tu fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Canciones especiales', 'En cualquier fiesta hay momentos álgidos que requieren de canciones especiales. Haz una lista de canciones para la llegada del homenajeado o para una entrega de premios o de regalos y pídele al responsable de la música que los ponga en ese momento.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Actividades de la fiesta', 'Amenizar la fiesta con propuesta y actividades divertidas es un acierto seguro y ayudarán a crear un ambiente desenfadado y divertido en el que todo el mundo lo va a pasar fenomenal.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Seguridad', 'Contrata seguridad o ten en cuenta cualquier elemento de seguridad que necesite tu fiesta.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Personal de limpieza', 'Recuerda reservar un equipo de limpieza para cuando tu fiesta haya terminado.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Mesa central', 'Una mesa en el centro del salón o bien en un extremo de este con diversos bocadillos que puedan servir de tentempié es muy buena opción.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Importancia de la mesa', 'La mesa es el punto fuerte de la fiesta y el foco principal al que prestar atención. No nos engañemos, por muy bonito que queramos dejar el espacio donde se celebre, la magia sucede en la mesa.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Mesa para regalos', 'A lado de la mesa de bocadillos se puede colocar una mesa más para los regalos, esta debe estar decorada también con algún mantel distintivo, la pared también debe estar decorada con figuras que representen esa celebración.');
insert into POST(id_post, seccion_post, titulo_post, cuerpo_post) value (null, 'OTRO', 'Música acorde', 'Elige música que vaya acorde con lo que se está celebrando, respetar los motivos de la celebración es vital.');

select * from post;