USE ATF;

DROP TABLE IF EXISTS LUGAR;

drop table if exists PERSONA;

DROP TABLE IF EXISTS USUARIO;

DROP TABLE IF EXISTS HORARIO;

DROP TABLE IF EXISTS TEMATICA;

DROP TABLE IF EXISTS CATEGORIA;

DROP table if exists SERVICIO;

DROP TABLE IF EXISTS POST;

DROP TABLE IF EXISTS SALON_FIESTA;

DROP TABLE IF EXISTS METODO_PAGO;

DROP TABLE IF EXISTS RELIGION;

DROP TABLE IF EXISTS TEMPLO;

DROP TABLE IF EXISTS PROVEEDOR;

DROP TABLE IF EXISTS ORDEN_COMPRA;

DROP TABLE IF EXISTS PRODUCTO;

drop table if exists PRODUCTO_PROVEEDOR;

DROP TABLE IF EXISTS DETALLE_COMPRA;

DROP TABLE IF EXISTS PUNTO_REFERENCIA;

DROP TABLE IF EXISTS DECORACION;

drop table if exists TIPO_FIESTA;

DROP TABLE IF EXISTS FIESTA;

DROP TABLE IF EXISTS HORARIO_SERVICIO;

DROP TABLE IF EXISTS CORTE_Y_COSTURA;

drop table if exists TRABAJO_CYC;

drop table if exists JEFATURA;

drop table if exists NOTARIA;

drop table if exists COORDENADA;

DROP TABLE IF EXISTS PRESUPUESTO;

DROP TABLE IF EXISTS CONTRATO;

drop table if exists RESERVA;

DROP TABLE IF EXISTS CITA;

drop table if exists PRODUCTO_SERVICIO;

DROP TABLE IF EXISTS AMBIENTE;

drop table if exists AMBIENTE_SALON;

drop table if exists SERVICIO_PRESUPUESTO;

drop table if exists PAGO;

drop table if exists PRODUCTO_PEDIDO;

drop table if exists ROL;

drop table if exists ROL_USUARIO;

drop table if exists PERMISO;

drop table if exists ROL_PERMISO;

DROP TABLE IF EXISTS CONTRATO_TERCERO;

DROP TABLE IF EXISTS SERVICIO_TIPO_FIESTA;

DROP TABLE IF EXISTS SERVICIO_TERCERIZADO;

DROP TABLE IF EXISTS ESTACIONAMIENTO;

drop table if exists CURSO_MATRIM;

DROP TABLE IF EXISTS INSCRIPCION_CUR_M;

DROP TABLE IF EXISTS ESTADO;

DROP TABLE IF EXISTS ESTADO_CONTRATO;

DROP TABLE IF EXISTS ESTADO_P_P;

DROP TABLE IF EXISTS ESTADO_PRESUPUESTO;

DROP TABLE IF EXISTS ESTADO_DETALLE;

DROP TABLE IF EXISTS TELEFONO;

DROP TABLE IF EXISTS IMAGEN;

DROP TABLE IF EXISTS DESCUENTO;

DROP DATABASE ATF;